---
title: "Final Project for Practical Machine Learning"
author: "Michael Nasatka"
date: "March 22, 2015"
output: html_document
---

Per the project description:

Background

Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement – a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website here: http://groupware.les.inf.puc-rio.br/har (see the section on the Weight Lifting Exercise Dataset). 



Data 

The data for this project come from this source: http://groupware.les.inf.puc-rio.br/har

The training data for this project are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv

The test data are available here: 

https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv


```{r}
library(randomForest)
library(gbm)
library(caret)

## reads in the training and testing data, sets working directory
pmlTesting <- read.csv("pml-testing.csv", row.names = 1)
pmlTraining <- read.csv("pml-training.csv", row.names = 1)
setwd("~/GitHub/Practical_Machine_Learning")

## removes covariates close to zero and variables with 90% missing values
nearzerotrain <- nearZeroVar(pmlTraining, saveMetrics = T)
cleantraining <- pmlTraining[, !nearzerotrain$nzv]
mostlymissingtrain <- sapply(colnames(cleantraining), function(x) if(sum(is.na(cleantraining[, x])) > 0.8*nrow(cleantraining)){return(T)}else{return(F)})
cleantraining <- cleantraining[, !mostlymissingtrain]

nearzerotest <- nearZeroVar(pmlTesting, saveMetrics = T)
cleantesting <- pmlTesting[, !nearzerotest$nzv]
mostlymissingtest <- sapply(colnames(cleantesting), function(x) if(sum(is.na(cleantesting[, x])) > 0.8*nrow(cleantesting)){return(T)}else{return(F)})
cleantesting <- cleantesting[, !mostlymissingtest]

## partitions cleaned training set into a training and cross validation set
set.seed(999)
inTrain = createDataPartition(cleantraining$classe, p = 3/4, list=FALSE)
training = cleantraining[inTrain,]
crossValidation = cleantraining[-inTrain,]

## train model with random forest for highly accuracy.
modfit <- train(classe ~ ., method="rf", data=training, importance=T, tuneLength=1, trControl = trainControl(method="cv", number=5))

## compute accuracy of training and cross validation set
trainingPred <- predict(modfit, training)
confusionMatrix(trainingPred, training$classe)

cvPred <- predict(modfit, crossValidation)
confusionMatrix(cvPred, crossValidation$classe)

## predict on the real testing set
pred <- predict(modfit,cleantesting)

pml_write_files = function(x){
  n = length(x)
  for(i in 1:n){
    filename = paste0("problem_id_",i,".txt")
    write.table(x[i],file=filename,quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
}

pml_write_files(as.character(pred))

```